zeabur/zbpack

- internal/nodejs/plan.go
Closes imaegoo/twikoo-zeabur#2
> fix(nodejs): command "instypes.tall" not found

- .editorconfig
- .github/workflows/commitlint.yml
- commitlint.config.js
- chore(lint): Add commitlint
- chore(lint/editorconfig): YAML accepts only Tab
- refactor(lint/commitlint): Subscope support
> ZEA-888: Implement commitlint for zbpack

- internal/dockerfile/plan.go
- internal/dockerfile/plan_test.go
- test(planner/docker): Test for plan
- refactor(planner/docker): Find EXPOSE reliably
- test(planner/docker): Extend the testcases
> refactor(planner/docker): Find EXPOSE reliably

- internal/php/composer.go
- internal/php/composer_test.go
- internal/php/identify.go
- internal/php/php.go
- internal/php/plan.go
- internal/php/plan_apt_test.go
- internal/php/plan_test.go
- refactor(planner/php): Refactor and add tests
- feat(planner/php): DetermineAptDependencies
> ZEA-1200: Add the missing dependencies to Debian image

- internal/python/plan.go
- fix(planner/python): Allow inst. multiple apt deps
- feat(planner/python): Add dependencies for pyzbar
> ZEA-1221: Add apt deps for pyzbar

- internal/static/static.go
Add CORS header on static plan type
> fix(static): Add `Access-Control-Allow-Origin` header

- internal/bun/plan.go
- pkg/types/plan.go
> chore: add bun framework detection

- internal/nodejs/package.go
- internal/nodejs/plan.go
> chore: Correct typos in zbpack

- internal/dotnet/plan.go
- internal/static/identify.go
> style: Use goimport for ordering imports

- internal/nodejs/identify.go
- internal/nodejs/plan.go
- tests/node-common-without-cache/.gitignore
- tests/node-common-without-cache/index.js
- tests/node-common-without-cache/package.json
- tests/node-common-without-cache/pnpm-lock.yaml
- tests/node-common-without-cache/zbpack.json
Linear: ZEA-2097 | Based on #169
> feat(planner/nodejs): Implement cache_dependencies switch

- internal/swift/identify.go
- internal/swift/plan.go
- internal/swift/swift.go
- pkg/types/plan.go
- pkg/zeaburpack/identifiers.go
- pkg/zeaburpack/image.go
- pkg/zeaburpack/packers.go
1. `brew install vapor`
2. `vapor new vapor-template`
3. `cd vapor-template/`
4. `zbpack .`
> feat: Add Swift provider and Vapor support

- internal/nodejs/plan.go
- internal/nodejs/waku/main.go
- pkg/types/plan.go
- pkg/zeaburpack/main.go
Add https://github.com/dai-shi/waku support.
> feat: Add Waku framework support

- internal/nodejs/__snapshots__/template_test.snap
- internal/nodejs/templates/template.Dockerfile
- feat(planner/nodejs): Add support for Node.js 12-14
- test(planner/nodejs): Update snapshot (corepack)
> ZEA-2394: add corepack support for Node.js 12

- internal/nodejs/plan.go
- internal/static/TransformServerless.go
- pkg/types/plan.go
Minimal Documentation Framework, powered by React + Vite.
https://github.com/wevm/vocs
> feat: support vocs

- internal/nodejs/plan.go
- internal/static/TransformServerless.go
- pkg/types/plan.go
https://github.com/web-infra-dev/rspress
Rspress is a static site generator based on [Rspack](https://rspack.dev/), rendered with the React framework.
> feat: add rspress support

- internal/nodejs/plan.go
- internal/static/TransformServerless.go
- pkg/types/plan.go
Add support Starlight
[Starlight](https://github.com/withastro/starlight) is a documentation website framework for [Astro](https://astro.build/).
Added support for displaying its logo when deployed on Zeabur.
- https://github.com/zeabur/service-icons/pull/7
> feat: support starlight

- .gitignore
Added `zbpack` to `.gitignore`
none
> chore: add zbpack to .gitignore

- .github/PULL_REQUEST_TEMPLATE.md
I think Zeabur need a PR template.
- Closes #
> chore: Added a PR template

- .gitignore
- internal/rust/identify.go
- internal/rust/plan.go
- internal/rust/rust.go
- internal/rust/template.Dockerfile
- pkg/zeaburpack/main.go
This issue implement rust serverless function.
- Closes ZEA-2540
> feat(planner/rust): Implement rust serverless

- internal/nodejs/plan.go
> fix(planner/nodejs): Check nuxt in dev dependencies

- internal/java/identify.go
- internal/java/java.go
Unchecked.
- Refactor a lot of if-statement to switch (IDE checked)
- Add "javaArgs" in zbpack.json to customize the `java -jar` arguments.
- Closes ZEA-2600
- Suggested label: enhacement
> feat(planner/java): Support custom Java argument

- internal/dart/dart.go
- internal/dart/identify.go
- pkg/types/plan.go
- pkg/zeaburpack/identifiers.go
- pkg/zeaburpack/main.go
- pkg/zeaburpack/packers.go
> feat: add Flutter support

- internal/python/__snapshots__/plan_test.snap
- internal/python/plan.go
- internal/python/plan_test.go
- pkg/types/plan.go
-  Support python tornado
- Closes #
> feat(planner/python): Support Tornado

- internal/php/plan.go
Only use major version for php.
- Closes #
> fix: php only use major version

- internal/nodejs/plan.go
- pkg/types/plan.go
Add [@zeabur/astro-adapter](https://www.npmjs.com/package/@zeabur/astro-adapter) support.
- Closes #
> feat: add `@zeabur/astro-adapter` support

- internal/ruby/plan.go
Make the linter CI happy.
- Suggested label: style
> chore(planner/ruby): Fix lint

- internal/nodejs/plan.go
Sometimes we just need Astro in devDependencies for static sites
- Closes #
> support astro in devDependencies for static sites

- internal/gleam/gleam.go
- internal/gleam/identify.go
- pkg/types/plan.go
- pkg/zeaburpack/identifiers.go
- pkg/zeaburpack/packers.go
Add [Gleam](https://gleam.run/) support.
- Closes #
> feat: add gleam support

- internal/python/plan.go
- internal/python/plan_test.go
- internal/python/python.go
- **refactor(planner/python): Better naming of ExplicitDependency function**
- **feat(planner/python): Add dependencies for Playwright**
- **feat(planner/python): Implement selenium support for Python**
Only Headless mode is supported.
- Closes ZEA-2903
- Suggested label: `enhancement`
> ZEA-2903: support playwright and selenium for python

- internal/dotnet/identify.go
- internal/dotnet/identify_test.go
> fix(planner/dotnet): Use snake_case in configuration key

- internal/static/static.go
> fix(planner/static): Use newer image to build Hugo

- internal/static/TransformServerless.go
> fix: don't delete `.well-known` dir

- internal/python/plan.go
> feat(python): add custom start command

- internal/ruby/__snapshots__/identify_test.snap
- internal/ruby/identify.go
- internal/ruby/identify_test.go
- internal/ruby/plan.go
- internal/ruby/plan_test.go
- internal/ruby/ruby.go
- **feat(planner/ruby): Allow customizing start command, build command, entry & version**
- **test(planner/ruby): Add snapshot test**
- **feat(planner/ruby): Generate according to the buildCmd and startCmd**
- Closes ZEA-3110
> ZEA-3110: Custom Start Command for Ruby

- internal/nodejs/plan.go
- internal/nodejs/plan_test.go
> fix(planner/nodejs): Missing RUN in custom install command

- internal/python/plan.go
> feat(planner/python): Support azure-cognitiveservices-speech

- internal/dart/dart.go
- internal/dart/identify.go
> feat: custom build command for dart provider

- go.mod
- go.sum
- internal/source/s3fs.go
- pkg/zeaburpack/plan.go
- pkg/zeaburpack/utils.go
```bash
export AWS_ACCESS_KEY_ID="xxx"
export AWS_SECRET_ACCESS_KEY="xxx"
export AWS_REGION="xxx"
zbpack -i s3://my-bucket/my-dir
2024/06/06 16:13:01 using submoduleName: my-dir
2024/06/06 16:13:02 
║ provider         │ go                                                 ║
║ goVersion        │ 1.21.4                                             ║
╚═══════════════════════════════════════════════════════════════════════╝
```
- Closes #
> feat: run zbplan on s3

- internal/bun/identify.go
- internal/dart/identify.go
- internal/deno/plan.go
- internal/dockerfile/plan.go
- internal/dotnet/plan.go
- internal/elixir/plan.go
- internal/java/plan.go
- internal/nodejs/package.go
- internal/nodejs/plan.go
- internal/php/composer.go
- internal/php/plan.go
- internal/python/plan.go
- internal/ruby/plan.go
- internal/rust/plan.go
- internal/static/identify.go
- internal/swift/plan.go
- internal/utils/encoding.go
- internal/utils/encoding_test.go
- pkg/plan/plan.go
- **feat(utils): Add ReadToUTF8 method**
- **refactor: Convert all UTF-16 inputs to UTF-8**
- Closes ZEA-3410
- Suggested label: enhancement?
> ZEA-3410: Convert to UTF-8 from UTF-16 for every files before comparing

- devbox.json
- devbox.lock
Update buildkit and add golangci-lint
- Closes #
> chore(devbox): Update buildkit and golangci-lint

- internal/python/plan.go
Install ImageMagick and add (maybe) necessary policy XML file for ImageMagick when detecting MoviePy.
- Closes ZEA-3525
> fix(planner/python): Install ImageMagick when detecting MoviePy

- devenv.lock
- devenv.yaml
- flake.lock
- **chore: Update devenv lock**
- **chore: Update flake lock**
- Closes #
> Update devenv and nix lockfile

- internal/python/identify.go
- internal/python/plan.go
- **feat(planner/python): Allow customizing entry**
- **feat(planner/python): Add app/__init__.py to the default search path**
- **refactor(planner/python): Optimize wsgi entrypoint handling**
- Closes ZEA-3604
> ZEA-3604: Implement "app/__init__.py" pattern

- internal/python/plan.go
- internal/python/python.go
> fix(python): reflex with poetry

- internal/source/githubfs.go
* Reads only the first 1 GiB of the given TAR.
* Remove unneeded `bytes.Buffer` – `tarfs` will copy the content.
- Closes ZEA-3936
> fix(source): Limit TAR size & remove unneeded copy

- internal/source/githubfs.go
- internal/source/githubfs_black_test.go
The TAR retrieved from GitHub may be corrupted. For example, I can see there is a package.json file, but I cannot read it. Therefore, I switched to zipfs, which might be more stable.
This commit also adds a new error message: "repo is too large," since we read the stream to the RAM now. Note that it may introduce $2n$ memory usage.
- Closes ZEA-4056
> refactor(githubfs): Use ZipFS

- internal/static/identify.go
- internal/static/static.go
- pkg/zeaburpack/image.go
- pkg/zeaburpack/main.go
Add containerized mode of static. Can be enabled with `FORCE_CONTAINERIZED`.
- Closes ZEA-4146
> ZEA-4146: Containerized static

- flake.lock
> chore: Update devenv lockfile

- pkg/zeaburpack/image.go
- pkg/zeaburpack/injection.go
- pkg/zeaburpack/injection_test.go
- pkg/zeaburpack/main.go
Separate buildImage and InjectDockerfile.
- Separated from #359
> Separate Dockerfile injection and buildImage

- internal/bun/bun.go
- internal/bun/identify.go
- internal/bun/plan.go
- internal/bun/plan_test.go
- internal/nodejs/__snapshots__/template_test.snap
- internal/nodejs/node.go
- internal/nodejs/package.go
- internal/nodejs/template_test.go
- internal/nodejs/templates/template.Dockerfile
- **feat(planner/bun): Implement Determine[Bun]Version**
- **feat(planner/nodejs): Pick BunVersion**
- Closes #348, Closes ZEA-4209
> ZEA-4209: Allow setting specific Bun version

- internal/bun/bun.go
- internal/dotnet/templates/nginx-runtime.Dockerfile
- internal/gleam/gleam.go
- internal/golang/golang.go
- internal/nodejs/__snapshots__/template_test.snap
- internal/nodejs/templates/template.Dockerfile
- internal/python/python.go
- internal/static/static.go
- internal/swift/swift.go
The latest buildkit requires all the "AS" to be uppercased.
> fix: "AS" must be uppercased

- tests/real_project_test.go
- tests/snapshots/nodejs-agent.txt
nodejs_agent has been removed.
> test: Clean up real_project_test

- pkg/zeaburpack/injection_test.go
- pkg/zeaburpack/parser.go
AST `AS` does not normalize.
- Closes SUP-720, SUP-719
> fix(zbpack): support AS lowercase

- internal/php/Dockerfile
- internal/php/config.go
- internal/php/identify.go
- internal/php/php.go
- internal/php/plan.go
- **fix(planner/php): Don't throw error if the optimization failed**
- **feat(planner/php): Allow disabling optimization**
- Closes ZEA-4277
> ZEA-4277: Allow disabling php cache

- internal/nodejs/plan.go
- internal/nodejs/plan_test.go
- tests/real_project_test.go
- tests/snapshots/nodejs-sveltekit-v2.txt
- **fix(planner/nodejs): Svelte on Containerized mode**
- **test: Add sveltekit-v2 e2e test**
- **chore: Update snapshot**
- Closes ZEA-4341
> ZEA-4341: Fix Svelte containerized start command

- internal/bun/identify.go
- internal/nodejs/plan.go
- tests/snapshots/bun-nextjs.txt
- tests/snapshots/node-astro.txt
- tests/snapshots/node-sveltekit.txt
- tests/snapshots/nodejs-a-lot-of-dependencies.txt
- tests/snapshots/nodejs-angular.txt
- tests/snapshots/nodejs-docusaurus.txt
- tests/snapshots/nodejs-expressjs.txt
- tests/snapshots/nodejs-foal.txt
- tests/snapshots/nodejs-nestjs.txt
- tests/snapshots/nodejs-nextjs.txt
- tests/snapshots/nodejs-nuejs.txt
- tests/snapshots/nodejs-nuxtjs.txt
- tests/snapshots/nodejs-payload.txt
- tests/snapshots/nodejs-qwik-city.txt
- tests/snapshots/nodejs-remix.txt
- tests/snapshots/nodejs-rspress.txt
- tests/snapshots/nodejs-slidev.txt
- tests/snapshots/nodejs-starlight.txt
- tests/snapshots/nodejs-sveltekit-v2.txt
- tests/snapshots/nodejs-umi.txt
- tests/snapshots/nodejs-vite-vanilla.txt
- tests/snapshots/nodejs-vitepress.txt
- tests/snapshots/nodejs-vocs.txt
- tests/snapshots/nodejs-waku.txt
- tests/snapshots/static-hexo.txt
- **fix(planner/bun): Add more determinations**
- **fix(planner/nodejs): Remove bunVersion fallback if bun is disabled**
- **chore: Update snapshot**
> Fixes of Bun planner

- gomod2nix.toml
- internal/bun/plan.go
- **chore: Update lockfile**
- **fix(planner/bun): Allow overriding Bun framework**
> Bun: allow overriding Bun framework (or force using Node.js framework)

- gomod2nix.toml
- internal/python/plan.go
- **chore: Update lockfile**
- **feat(planner/python): Support "psycopg"**
- Closes ZEA-4474
> feat: Support psycopg in Python planner

- internal/bun/bun.go
- internal/bun/identify.go
- internal/nodejs/plan.go
- **feat(planner/bun): Implement Bun text-based lockfile**
- **feat(planner/nodejs): Implement Bun text-based lockfile**
- Closes ZEA-4483
> ZEA-4483: Implement bun.lock

- internal/nodejs/node.go
- internal/nodejs/node_test.go
- internal/nodejs/plan.go
- internal/nodejs/templates/template.Dockerfile
- pkg/types/plan.go
- tests/real_project_test.go
- tests/snapshots/nodejs-expressjs.txt
- tests/snapshots/nodejs-foal.txt
- tests/snapshots/nodejs-medusa.txt
- tests/snapshots/nodejs-nestjs.txt
- tests/snapshots/nodejs-nuejs.txt
* Refactoring Node.js Start and Build command
* Implement Medusa support with multi-layer Dockerfile
- Closes ZEA-4514
> ZEA-4514: Implement Medusa support

- pkg/plan/plan.go
```
pan93412@panmac2:/Volumes/Dev/Zeabur/zbpack/ > zbpack -i .         
2025/01/23 23:24:55 using submoduleName: zbpack
║ provider         │ go                                                 ║
║ goVersion        │ 1.22.0                                             ║
║ entry            │ cmd/zbpack/main.go                                 ║
╚═══════════════════════════════════════════════════════════════════════╝
pan93412@panmac2:/Volumes/Dev/Zeabur/zbpack/ > ZBPACK_PLAN_TYPE=nodejs zbpack -i .
2025/01/23 23:25:00 using submoduleName: zbpack
2025/01/23 23:25:00 Failed to …
```
> feat(planner): Implement ZBPACK_PLAN_TYPE flag

- internal/swift/swift.go
Update Dockerfile to https://github.com/vapor/template/blob/51f1dc7f5ca020eef34622ba38ba4209b7bf4d92/Dockerfile
- Closes ZEA-4554 (SUP-1424)
- Suggested label: enhancement (swift 6)
> feat(packers/swift): Update Dockerfile template of Vapor

- internal/nodejs/__snapshots__/template_test.snap
- internal/nodejs/templates/template.Dockerfile
https://github.com/nodejs/corepack/issues/612
Upgrading corepack to the latest version fixes this issue.
- Closes ZEA-4555, SUP-1423
> fix(packers/nodejs): Install the latest version of corepack

- internal/static/identify.go
> feat(planner/static): Add hugo.yaml and hugo.json

- internal/python/plan.go
For a `uv` project, we can determine the Python version correctly.
- Closes ZEA-4931
> refactor(planner/python): Make determinePythonVersion generic
