zeabur/zbpack

internal/dockerfile/dockerfile.go, internal/dockerfile/dockerfile_test.go, internal/dockerfile/plan.go, internal/dockerfile/plan_test.go
This issue was produced in da9e8122ace0247cd9f6d5266f2ba61a3be2e78d.
It returns the “filename” rather than the actual content,
so we get the “Dockerfile” instead of the content of “Dockerfile”
when calling `GenerateDockerfile()`.
=> fix(planner/docker): Return the actual content

cmd/zbpack/main.go
Print a simple usage text to the terminal when zbpack is run without any arguments
Check for the number of arguments and if its less than 2, the command will not execute and exit the program. This provides a better experience for the user. To run zbpack in the current dir, you can do `zbpack  .`
Closes #60
=> feat(cli): Print usage information in the terminal

internal/dotnet/dotnet.go, internal/dotnet/dotnet_test.go, internal/dotnet/identify.go, internal/dotnet/identify_test.go, internal/dotnet/plan.go, internal/dotnet/plan_test.go, pkg/types/plan.go, pkg/zeaburpack/identifiers.go, pkg/zeaburpack/packers.go, tests/dotnet-samples/dotnetapp/Program.cs, tests/dotnet-samples/dotnetapp/dotnetapp.csproj
Add support for .NET applications
With this PR, you will be able to generate docker images for dotnet applications. It includes test cases with a sample dotnet application. Please note that this is still a minimum implementation, and it supports simple dotnet applications. In future, we can add more revisions to support more complex dotnet applications with multiple build paths. 
1. Dotnet console 
2. ASP.NET Web App
3. ASP.NET Web API
**Not tested for older .NET framework versions**
Please review, feedback is appreciated. 
Relates to #64
=> [Draft] feat(planner): Add .NET support

internal/python/plan.go, internal/python/plan_test.go
Fix the CI issue of #70 
- test(planner/python): Order must be deterministic
- fix(planner/python): Order is not deterministic
=> fix(planner/python): Unstable result of Python DeterminePackageManager

internal/nodejs/plan.go, pkg/types/plan.go
add Docusaurus️ framework support
=> feat(plan/nodejs): add Docusaurus️ framework support

internal/dotnet/dotnet.go, internal/dotnet/identify.go, internal/dotnet/plan.go, internal/dotnet/plan_test.go, internal/dotnet/templates/nginx-conf.Dockerfile, internal/dotnet/templates/nginx-runtime.Dockerfile, internal/dotnet/templates/template.Dockerfile, pkg/types/plan.go
Add support for Blazor WebAssembly and configure a default port.
- Added support for Blazor wasm. Blazor wasm serves static files, unlike other .NET technologies, and in order to serve the static files we need a server like nginx. 
- Configured the Dockerfile with a default port 8080, this can be overwritten by suppling a new value during runtime. 
Closes #66
=> feat(planner/dotnet): Add framework specific support

commitlint.config.js, go.mod, go.sum, pkg/zeaburpack/image.go
Something to optimize :
Now:
```
BenchmarkResolveEnvVariable_Basic
BenchmarkResolveEnvVariable_Basic-8               108836              9893 ns/op           10307 B/op        101 allocs/op
BenchmarkResolveEnvVariable_Complex
BenchmarkResolveEnvVariable_Complex-8             158244              8486 ns/op            9493 B/op        121 allocs/op
PASS
BenchmarkResolveEnvVariable_Basic
BenchmarkResolveEnvVariable_Basic-8               279270              4193 ns/op            3831 B/op         50 allocs/op
BenchmarkResolveEnvVariable_Complex
BenchmarkResolveEnvVariable_Complex-8             440034              2707 ns/op            2664 B/op         44 allocs/op
PASS
```
=> ZEA-1367: Correct the reference order of environment variables

internal/nodejs/plan.go
```
20:17:02#10 [6/6] RUN apt-get update && apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm1 libasound2 libpangocairo-1.0-0 libxss1 libgtk-3-0 libxshmfence1 libglu1 && groupadd -r puppeteer && useradd -r -g puppeteer -G audio,video puppeteer && chown -R puppeteer:puppeteer /src && mkdir /home/puppeteer && chown -R puppeteer:puppeteer /home/puppeteer && USER puppeteer &&
20:17:02#10 0.228 /bin/sh: 1: Syntax error: end of file unexpected
20:17:02#10 ERROR: process "/bin/sh -c apt-get update && apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm1 libasound2 libpangocairo-1.0-0 libxss1 libgtk-3-0 libxshmfence1 libglu1 && groupadd -r puppeteer && useradd -r -g puppeteer -G audio,video puppeteer && chown -R puppeteer:puppeteer /src && mkdir …
```
=> fix(planner/nodejs): Fix build failed when need puppeteer and no build script

pkg/zeaburpack/ref.go, pkg/zeaburpack/ref_test.go
Fixes:
```
Expected :scratch
Actual   :zeabur.tld/proxyowo/library/scratch
```
=> fix(lib): Don't construct if ref is scratch

internal/dockerfile/identify.go, internal/dockerfile/identify_test.go
- fix(planner/dockerfile): Match() at prefixed / suffixed Dockerfile
- test(planner/dockerfile): Test our new Match()
=> ZEA-1926: Adapt Match() for monorepo build

internal/python/__snapshots__/plan_test.snap, internal/python/plan.go, internal/python/python.go
Run install commands in the following order to fully use Docker's layer caching:
1. install the package manager if not pip
2. install the wsgi if needed
3. copy the dependency files
4. install dependency
5. copy all files
6. run build command (for example, Django's collect static command)
=> perf(planner/python): Optimize Python install command order for layer caching

internal/ruby/plan.go
=> fix(planner/ruby): Support single-quoted version

pkg/zeaburpack/utils.go
=> feat(utils): Print multiline command in plan table

internal/static/identify.go, tests/static-hugo-config-dir/archetypes/default.md, tests/static-hugo-config-dir/config/_default/hugo.toml, tests/static-hugo-config-dir/public/categories/index.xml, tests/static-hugo-config-dir/public/index.xml, tests/static-hugo-config-dir/public/sitemap.xml, tests/static-hugo-config-dir/public/tags/index.xml
Enhance the detection of the Hugo framework by searching in `config/_default`
=> feat(planner/static): Support hugo configuration directory mode & test case

pkg/zeaburpack/main.go
Currently, if we want to deploy a project in serverless way (with `.zeabur/output`), we only support two scenarios:
1. `.zeabur/output` already in repo.
2. zbpack calling `TransformServerless` to generate a `.zeabur/ouput`
This Pull Request enables users or framework authors can generate `.zeabur/output` at build time, then deploy as serverless format.
=> fix(pkg): Copy zeabur output from image to host

internal/python/__snapshots__/plan_test.snap, internal/python/identify.go, internal/python/plan.go, internal/python/plan_test.go, tests/python-streamlit/streamlit_app.py
1. Projects with `zbpack.json` including `{"streamlit": {"entry": "<entry>"}}`. <entry> will be used.
- `requirements.txt` is required if there is no any file named `app.py`, `main.py` or `streamlit_app.py`.
2. For `app.py`, `main.py`, `streamlit_app.py` files including `import streamlit`: such file will be used.
For all Streamlit projects, we install `streamlit` automatically even there is no `requirements.txt`.
We run it with `<pkg-manager-pre-args> streamlit run <entry> --server.port=8080 --server.address=0.0.0.0`, while `8080` is Zeabur's default listening port.
=> feat(planner/python): Implement streamlit support

internal/golang/identify.go, internal/golang/plan.go, internal/nodejs/plan.go, internal/python/plan.go, internal/utils/config.go
- feat(planner/golang): Inject project configuration
- feat(utils): Add "GetExplicitServerlessConfig" function
- refactor(planner): getServerless() calls GetExplicitServerlessConfig
=> ZEA-2417: ZBPACK_SERVERLESS=1 with zbpack.json

internal/bun/identify.go, internal/nodejs/node.go, internal/nodejs/plan.go
```
║ provider         │ bun                                                ║
║ serverless       │ true                                               ║
║ bun              │ true                                               ║
║ packageManager   │ bun                                                ║
║ framework        │ none                                               ║ …
```
=> fix: Use bun as pkg manager for Node.js provider

internal/zbpack/helper.go, internal/zbpack/zbpack.go
- feat(cli): Allow passing --submodule <name>
- feat(cli): Print submoduleName for debugging
- refactor(cli): Use lo for pointer value
=> ZEA-2448: Customizable submodule name in CLI

go.mod, go.sum, pkg/zeaburpack/ref.go
- refactor(lib): Migrate docker/distribution/* to distribution/*
- style(lib): Correct sentence according to JetBrains' suggestions
=> ZEA-2458: docker/distribution has been deprecated

internal/python/plan.go
Add the start command prefix (`poetry run`, etc.) to `RUN python manage.py collectstatic --noinput\n`.
Also, correct the installation order for `pip install -r requirements.txt`.
I have tested both Poetry and Pip case.
- Closes ZEA-2547
=> fix(planner/python): Add start command prefix to Django collectstatic

internal/nodejs/plan.go
I removed a duplicate `Vite` and reordered the frameworks based on Vite as follows:
```
nuxt -> waku -> vitepress -> vite
```
This order was proposed in issue #203.
-  Fixed #203
=> refactor(planner/nodejs): Reorder frameworks priority

internal/rust/template.Dockerfile
This issue fixes rust build missing binary file due to old serverless export method using fixed SubmoduleName.
- Closes ZEA-2557
=> fix(plan/rust): Fix file missing due to rust build binary name

internal/php/__snapshots__/template_test.snap, internal/php/identify.go, internal/php/php.go, internal/php/plan.go, internal/php/template_test.go
- Determine the extensions to install in the plan stage and add it to `exts` planMeta.
- Install extensions early (before `COPY`) to leverage caches.
- 'composer.json' is not the "single source of truth" for the extension installation.
- Don't run `apt install` if there is no `aptDeps`.
- Add the `exts` test in snapshot.
- Closes ZEA-2569
- Suggested label: `bug` `enhancement`
=> ZEA-2569: Refactor PHP extension installer

internal/rust/template.Dockerfile
This issue fixes binary rename when rust plan compiling.
- Closes ZEA-2576
=> fix(plan/rust): Fix rust compile binary rename

internal/php/__snapshots__/template_test.snap, internal/php/php.go
Use `install-php-extensions` to install extensions to simplify the installation of dependencies.
- Closes ZEA-2581
- Suggested label: `enhancement` (or `bug)
=> ZEA-2581: install php extensions

internal/python/plan.go, internal/python/plan_test.go
It is for fixing such cases:
FastAPI(   # no trailing ')'
name="app"
)
- Closes ZEA-2586
=> fix(planner/python): Matched ) is not required

internal/source/githubfs_black_test.go, pkg/zeaburpack/plan.go
- Correct the error handling in black test, and adds some logs for contents.
- Don't panic if the GitHubFS can't create properly.
- Don't `path.Join` for a `http://` path.  
- Closes ZEA-2590
=> ZEA-2590: Fix GitHubFS issues

internal/nodejs/nextjs/function.go, internal/nodejs/nextjs/main.go, internal/zbpack/zbpack.go
`golangci-lint` reports `unused-parameter` for some snippets. This PR fixes it.
- Closes #
=> fix: Linter reports "unused-parameter"

internal/nodejs/__snapshots__/template_test.snap, internal/nodejs/plan.go, internal/nodejs/plan_test.go, internal/php/plan.go, internal/python/version.go, internal/python/version_test.go, internal/utils/version.go, internal/utils/version_test.go
This PR generalizes the semver modules across numerous planners to utils/version.go.
- Closes ZEA-2651
=> ZEA-2651: Refactor all SemVer logics

internal/nodejs/plan.go
Disable the dependency copying stage if the monorepo (`pnpm-workspace`, `packages` folder) is detected.
- Closes ZEA-2700
=> fix(planner/nodejs): Disable cache if monorepo detected

internal/nodejs/remix/main.go
The //go:embed instruction has been removed in f7776feaf916a113fb2130cbde980eefcc561cea
- Fix CI https://github.com/zeabur/zbpack/actions/runs/8818109338/job/24206135890
- Suggested label: improvement
=> fix(planner/nodejs): Remove embed

internal/dotnet/dotnet.go, internal/dotnet/identify.go, internal/dotnet/identify_test.go, internal/dotnet/templates/template.Dockerfile
Add a `dotnet.submoduleDir` configuration that allows specify the module directory manually without changing the Docker context directory.
Tested:
- `dotnetapp/dotnetapp.csproj`
- `dotnetapp/dotnetapp/dotnetapp.csproj` (with the first `dotnetapp` as submodule name, the second `dotnetapp` as submodule directory)
- `myexampleproject/dotnetapp/dotnetapp.csproj` (with the first `myexampleproject` as submodule name, the second `dotnetapp` as submodule directory)
- Closes ZEA-2931
- Suggested label: `enhancement`
=> feat(planner/dotnet): Support monorepo

internal/dotnet/dotnet.go, internal/dotnet/identify.go, internal/dotnet/identify_test.go, internal/dotnet/plan_test.go, internal/dotnet/templates/template.Dockerfile, internal/php/plan_test.go
- Fix the tests to match new behaviors
- [fix(planner/php): Add config to GetPHPVersion](https://github.com/zeabur/zbpack/pull/254/commits/3c2a3e6366f84b3079d9aa6717277428135be698)
- [fix(planner/dotnet): Correct assert.Equal order](https://github.com/zeabur/zbpack/pull/254/commits/328af3e9fdfc662aea99738f876c51ee7e8c2764)
- [test(planner/dotnet): Entrypoint contains extension now](https://github.com/zeabur/zbpack/pull/254/commits/0fa1e6ca0c4ddde252a4719cca54c930931b8830)
- Do not panic if something wrong in `PlanMeta()`
- [fix(planner/dotnet): Fall back to other planners instead of panic](https://github.com/zeabur/zbpack/pull/254/commits/2c933a89357beab003ecc159a78cfcfcd6ebf090)
- Allow specify what project to use with `SubmoduleName`
- [feat(planner/dotnet): Support picking project …
=> Fix CI and panics

internal/nodejs/plan.go, internal/nodejs/template_test.go, internal/nodejs/templates/template.Dockerfile
Reinstall node_modules with `--production` flag after build. 
So we can cleanup the dependencies which is unused in runtime.
- Closes #
=> fix(nodejs): cleanup devDeps after build

internal/nodejs/plan.go, internal/nodejs/plan_test.go, pkg/plan/config.go, pkg/types/plan.go
- **feat(planner): Add `install_command` configuration**
- **feat(planner/nodejs): Implement `install_command`**
* No cache in `install_command`.
* `install_command` overrides the package manager installation commands, such as `yarn install`
* Dependencies are still installed.
- Closes ZEA-3167
=> ZEA-3167: Node.js: Customize InstallCommand

internal/python/identify.go
For projects containing `pyproject.toml` and `Pipfile`, it should be considered as
a potential Python project and should generate its PlanMeta.
- Closes ZEA-3226
- Suggested label: `bug`
=> fix(planner/python): Consider "pyproject.toml" and "Pipfile"

internal/python/plan.go, internal/python/plan_test.go
When detecting `python_version` in Pipfile, we pick that `python_version` to deploy.
- Closes ZEA-3340
=> ZEA-3340: support python_version field in pipenv

internal/python/plan.go, internal/python/plan_test.go
Allow setting the Python version with `ZBPACK_PYTHON_VERSION` or
```json
{
"python": {
"version": "3.12"
}
}
```
- Closes ZEA-3339
=> ZEA-3339: Support python.version configuration

go.mod, go.sum, internal/nodejs/__snapshots__/template_test.snap, internal/nodejs/node.go, internal/nodejs/package.go, internal/nodejs/plan.go, internal/nodejs/plan_test.go, internal/nodejs/template_test.go, internal/nodejs/templates/template.Dockerfile
This PR implements the discovery and building of Monorepo projects that are built with pnpm or Yarn workspaces.
Previously, we determined the application to build based solely on the root directory, which is usually the project repository. However, a repository may consist of multiple applications, and the old design did not work well in this situation.
Now, we introduce two new concepts: Project and Application. A "Project" typically refers to the entire repository, which contains common configuration like the package manager, linters, and zbpack.json. An "Application" is the application to deploy on Zeabur, which may be a subdirectory of a repository or the "Project" itself. It contains the dependencies of frameworks (like Next.js), the build commands, and the start commands.
Note that …
=> ZEA-3468: Node.js Monorepo Native Support

internal/php/identify.go, internal/php/plan.go, internal/php/plan_apt_test.go, internal/php/plan_test.go
- **feat(planner/php): Install Node.js if `package.json` exists**
- **feat(planner/php): Run npm run build if there is "build" script**
- **fix(planner/php): Make default start command a function**
- Closes ZEA-3493
=> ZEA-3493: PHP Planner supports npm build case

internal/python/__snapshots__/plan_test.snap, internal/python/plan.go, internal/python/plan_test.go
- **feat(planner/python): Implement npm toolchain and npm build support**
- **feat(planner/python): Allow customizing build command**
https://github.com/dali1756/5xcamp without `static` (artifacts) and `staticfiles` (Django collectstatic):
`ZBPACK_BUILD_COMMAND` which customizes build command:
`ZBPACK_START_COMMAND` which allows calling the default start command and our customized command:
- Closes ZEA-3466
=> ZEA-3466: Python planner supports npm build case

internal/source/githubfs.go, internal/source/githubfs_black_test.go, internal/zbpack/helper.go, pkg/zeaburpack/utils.go
- **feat(source): Allow specifying reference in GitHubFS** (`source.GitHubRef()`)
- **feat(lib): Allow specifying reference in URL** (format: `https://github.com/owner/repo#ref`)
- **feat(cli): Handle github ref case** (`repo#ref`'s submodule name is `repo`)
- Closes ZEA-3543
=> ZEA-3543: Add Git Reference support for GithubFS (and CLI support)

internal/nodejs/plan.go
- **refactor(planner/nodejs): Turn userAppDir "/" to ""**
- **fix(planner/nodejs): Save config entry to ctx.Serverless**
- **feat(planner/nodejs): Disable serverless if app root is empty**
**No serverless enabled in Next.js monorepo**
```
(devenv) bash-5.2$ zbpack -i .
2024/07/09 11:50:11 using submoduleName: turborepo-basic
2024/07/09 11:50:11 
║ provider         │ nodejs                                             ║
║ packageManager   │ pnpm                                               ║
║ framework        │ next.js                                            ║ …
```
=> ZEA-3556: Disable serverless for Monorepo

internal/php/plan.go
https://github.com/zeabur/laravel-template (no any ext- package installed)
```
║ provider         │ php                                                ║
║ app              │ default                                            ║
║ property         │ 1                                                  ║
║ buildCommand     │ npm install && npm run build                       ║
║ startCommand     │ _startup(){ nginx; php-fpm; }; …
```
=> feat(planner/php): Install pdo_pqsql by default

internal/rust/plan.go, internal/rust/rust.go, internal/rust/rust_test.go, internal/rust/template.Dockerfile, internal/rust/template_test.go
- **refactor(planner/rust): Rewrite Rust planner**
- **feat(planner/rust): Implement legacy zeabur-preserve**
Add configuration:
```go
// ConfigRustEntry is the key for the binary entry name of the application.
//
// If this key is not set, the default value is the binary with the submodule name.
// If there is no such submodule, it picks the first binary it found.
const ConfigRustEntry = "rust.entry"
// ConfigRustAppDir is the key for the directory of the application.
//
// If this key is not set, the default value is the current directory – "/".
const ConfigRustAppDir = "rust.app_dir"
// ConfigRustAssets is the key for the assets of the application.
// It is an array.
//
// The assets will be copied to the root of the application.
const ConfigRustAssets = "rust.assets"
``` …
=> ZEA-3456: Reimplement rust planner

pkg/zeaburpack/parser.go, pkg/zeaburpack/parser_test.go
Improve `fromStatementRegex` to cover `--platform=.+?`.
- Closes ZEA-3642
=> fix(lib): Support parsing of `--platform`

internal/gleam/gleam.go
Upgrade Gleam to v1.3.2, which is [the latest version in the GitHub registry](https://github.com/gleam-lang/gleam/pkgs/container/gleam/versions?filters%5Bversion_type%5D=tagged).
- Closes #325
=> feat(planner/gleam): Upgrade Gleam to v1.3.2

internal/nodejs/plan.go, internal/nodejs/plan_test.go
Determine the output directory of Vitepress by the `build` script:
```json
{
"scripts": {
"build": "vitepress build docs"
}
}
```
Here, the argument `docs` is the directory the docs is placed at.
- Closes ZEA-3712
=> feat(planner/nodejs): Determine Vitepress output directory from build script

internal/golang/golang.go, internal/golang/golang_test.go, internal/golang/plan.go, internal/golang/plan_test.go
Allow specifying the build command and `ENABLE_CGO` flag, making Go planner more useful.
```
$ ZBPACK_BUILD_COMMAND="go generate ./..." ZBPACK_CGO=true BUILDKIT_HOST=docker-container://buildkitd zbpack . 
2024/07/30 12:42:34 using submoduleName: zbpack
2024/07/30 12:42:34 environment variables to pass: map[]
║ provider         │ go                                                 ║
║ entry            │ cmd/zbpack/main.go                                 ║
║ buildCommand     │ go generate ./...                                  ║ …
```
=> feat(planner/golang): Support build command and CGO

gomod2nix.toml, internal/bun/identify.go, internal/nodejs/__snapshots__/template_test.snap, internal/nodejs/node.go, internal/nodejs/plan.go, internal/nodejs/plan_test.go, internal/nodejs/template_test.go, internal/nodejs/templates/template.Dockerfile, pkg/types/plan.go, pkg/zeaburpack/main.go
- Support [Nitropack](https://nitro.unjs.io).
- Allow running Nitro-based applications (Nuxt.js, Nitropack) as Bun server (if `SERVERLESS` is disabled).
- Allow building Nitropack as a serverless application.
- Closes ZEA-3822
=> ZEA-3822: Implement planning of a plain Nitro application

internal/nodejs/node.go, internal/nodejs/plan.go, internal/nodejs/plan_test.go, internal/nodejs/template_test.go, internal/nodejs/templates/template.Dockerfile, pkg/types/plan.go, pkg/zeaburpack/main.go
- Support SolidStart v1. It has been rewritten to Nitro (Vinxi), so I handle it in the separated logic.
- Refactor some Nitro logic to be generic.
- Closes ZEA-3587
=> ZEA-3857: Support new Nitro-based SolidStart package

internal/nodejs/plan.go
- Support Node v22
- Set default Node.js version to v20
- Closes none
=> chore(planner/nodejs): Upgrade default Node version to 20

devenv.nix, internal/nix/Dockerfile.tmpl, internal/nix/identify.go, internal/nix/identify_test.go, internal/nix/nix.go, pkg/types/plan.go, pkg/zeaburpack/identifiers.go, pkg/zeaburpack/image.go, pkg/zeaburpack/main.go, pkg/zeaburpack/packers.go
If the project contains a `flake.nix`, we try to build Nix image from this file.
The following output attributes are supported, regardless of letter case.
* `packages.<arch>-linux.dockerImage`
* `packages.<arch>-linux.docker-image`
* `packages.<arch>-linux.docker`
* `packages.<arch>-linux.image`
* `packages.<arch>-linux.container`
Note that:
- The build-time variable is not supported at the moment (which is also not encouraged by Nix's pure evaluation).
- No cache available now. Cachix has not been integrated into this planner yet.
- Closes ZEA-3827
=> ZEA-3827: zbpack: Nix planner and packer

gomod2nix.toml, internal/rust/plan.go, internal/rust/rust.go, internal/rust/template.Dockerfile, internal/rust/template_test.go
- **chore: Update lockfile**
- **feat(planner/rust): Support Build/Start/Prestart commands**
- Closes ZEA-3851
=> ZEA-3851: Build, Start, and Pre-start command in Rust

devenv.lock, devenv.yaml, flake.lock, gomod2nix.toml
Update devenv and Nix flake lock.
`gomod2nix`'s `nixpkgs` input has been set to follow the root `nixpkgs`.
- Closes #
=> chore: Update Nix dependencies

internal/nodejs/plan.go, internal/nodejs/plan_test.go
For example, `pnpm -C ../ run build && vitepress build`.
- Closes ZEA-4017
=> fix(planner/nodejs): Determine build command concat with &&

gomod2nix.toml, internal/source/githubfs.go, internal/source/githubfs_black_test.go
```
$ zbpack -i https://github.com/naiba/nezha
2024/09/17 20:54:58 using submoduleName: nezha
2024/09/17 20:54:59 
║ provider         │ docker                                             ║
║ expose           │ 8080                                               ║
...
```
- Closes ZEA-4056
- Suggested label: `bug`
=> ZEA-4056: Optimize folder find logic in githubfs

gomod2nix.toml, internal/static/static.go, pkg/plan/plan.go, pkg/plan/plan_test.go
- **fix(static): Containerized static for other frameworks**
- **chore: Update lockfile**
- **feat(plan): Add "serverless" field**
- Closes ZEA-4164
=> ZEA-4164: zbpack static empty planmeta handling

internal/dockerfile/dockerfile_test.go, internal/dockerfile/identify.go, internal/dockerfile/plan.go, internal/dockerfile/plan_test.go
Env: 
```
ZBPACK_DOCKERFILE_NAME="dbrunner-service" zbpack -i /tmp/backend-go/
2024/10/08 11:47:32 using submoduleName: backend-go
2024/10/08 11:47:32
║ provider         │ docker                                             ║
║ expose           │ 8080                                               ║
║ content          │ FROM golang:1.22-alpine3.20 AS builder             ║
║                  │                                                    ║
║                  │ WORKDIR /app                                       ║
║                  │ …
```
=> ZEA-4154: Allow specifying Dockerfile with environment variables

internal/dart/identify.go, internal/nodejs/plan.go
Useful for packers to determine if we should build a static artifact
as a serverless bundle (`.zeabur`). If `serverless` is `false`, we
should fallback to the classial containerized (in another word, Nginx) mode.
- **feat(planner/nodejs): Add "serverless" field to static artifact**
- **feat(planner/dart): Add "serverless" field to static artifact**
- Related to ZEA-4175
=> Add serverless field to static artifact

gomod2nix.toml, internal/dart/identify.go, internal/nodejs/plan.go
There may be a weird case:
serverless: false
outputDir: "/some/where"
It introduces some bugs for Zeabur. Not sure if this is the root cause.
=> fix(planner): when serverless is false, outputDir must be empty

gomod2nix.toml, internal/python/__snapshots__/plan_test.snap, internal/python/pkgmanager.go, internal/python/plan.go, internal/python/plan_test.go, internal/python/python.go, pkg/types/plan.go, tests/snapshots/python-django-static-whitenoise.txt, tests/snapshots/python-django-static.txt, tests/snapshots/python-django.txt, tests/snapshots/python-fastapi.txt, tests/snapshots/python-flask-mysql.txt, tests/snapshots/python-flask-static.txt, tests/snapshots/python-flask.txt, tests/snapshots/python-hnswlib.txt, tests/snapshots/python-streamlit.txt, tests/snapshots/python-zba651.txt
- **test(planner/python): Pass "config" to pythonPlanContext in tests**
- **refactor(planner/python): Simplify DeterminePackageManager**
- **feat(planner/python): Support uv package manager**
- **feat(planner/python): Allow specifying package manager**
- **test(python): Add uv tests**
- **fix(planner/python): Dockerfile issues**
- **feat(zbpack): Ignore more files in zbpack**
Add a new configuration (`python.package_manager`) to specify the package manager of this Python application.
- Closes ZEA-4300
=> Implement Python "uv" support

gomod2nix.toml, internal/python/plan.go, tests/snapshots/python-django-static-whitenoise.txt, tests/snapshots/python-django-static.txt, tests/snapshots/python-django.txt, tests/snapshots/python-fastapi.txt, tests/snapshots/python-flask-mysql.txt, tests/snapshots/python-flask-static.txt, tests/snapshots/python-flask.txt, tests/snapshots/python-hnswlib.txt, tests/snapshots/python-streamlit.txt, tests/snapshots/python-zba651.txt
Both mysqldb and psycog2 requires Clang now.
=> feat(planner/python): Install clang by default

internal/golang/plan.go, internal/golang/plan_test.go
Add a new config `ZBPACK_GO_ENTRY` (`go.entry`) to allow users specifying the entry point of application explicitly.
Useful for replicas (`app-1`, `app-2`, `app-3`) and custom structure of code.
- Closes ZEA-4416
=> feat(planner/golang): Allow specifying the entry point of a Go application

internal/python/__snapshots__/plan_test.snap, internal/python/plan.go, internal/python/python.go, tests/real_project_test.go, tests/snapshots/python-django-static-whitenoise.txt, tests/snapshots/python-django-static.txt, tests/snapshots/python-django.txt, tests/snapshots/python-fastapi.txt, tests/snapshots/python-flask-mysql.txt, tests/snapshots/python-flask-static.txt, tests/snapshots/python-flask.txt, tests/snapshots/python-hnswlib.txt, tests/snapshots/python-streamlit.txt, tests/snapshots/python-zba651.txt
- **fix(planner/python): Remove bad caching**
- **chore: Update E2E test repo**
- **chore: Update snapshot**
- Closes ZEA-4475
=> ZEA-4475: Python: Do not cache dependency installation layer

internal/nodejs/node.go, internal/nodejs/node_test.go, internal/nodejs/plan.go, internal/nodejs/templates/template.Dockerfile, tests/real_project_test.go, tests/snapshots/nodejs-medusa-zb.txt
There are some modules that needs the source code tree. Therefore, we will not only copy `.medusa/server` now.
This reverts commit 4c59e19952edccb594ea16e3564801df2524d946.
- Experiments
=> revert(planner/nodejs): Implement multi-layer build for Node.js

gomod2nix.toml, internal/nodejs/__snapshots__/template_test.snap, internal/nodejs/templates/template.Dockerfile
Do not install the latest Corepack, as it is not compatible with older Node.js runtimes (SUP-1441).
Since we use Corepack solely for installing the appropriate package manager, the integrity check does not seem very important.
- Closes ZEA-4570
=> ZEA-4570: Do not let corepack check integrity key

gomod2nix.toml, internal/bun/bun.go, internal/bun/plan.go, internal/nodejs/plan.go, pkg/types/plan.go, tests/snapshots/bun-hono.txt
- **chore: Update gomod2nix lockfile**
- **refactor(planner/bun): Merge Bun/hono logic to Node.js**
- **fix(planner/nodejs): Improve Hono support for Node.js**
- **test: Update snapshot**
- Closes ZEA-4609
=> ZEA-4609: Merge Bun/Hono logic to Node.js planner

internal/golang/golang.go
We COPY all the stuff first.
`go.mod` case:
```
// lib/leakless
replace github.com/ysmood/leakless => ./lib/leakless
```
- Closes ZEA-4659
=> fix(planner/golang): Allow go.mod pointing to the local directory

internal/rust/plan.go, internal/rust/rust_test.go, schema/zbpack.json
- **refactor(planner/rust): Use the standard app_dir**
- **feat: Add zbpack JSON schema**
- Closes ZEA-4455
=> ZEA-4455: zbpack.json schema

internal/nodejs/plan.go
See SUP-2010, npm changed the CI installation behavior.
- Closes ZEA-4828
=> fix(planner/nodejs): vite can be in dependencies

pkg/zeaburpack/plan.go
Allow specifying the root directory for Git and S3 source.
- Closes ZEA-5982
=> fix(zbpack): Add "subpath" option

internal/dockerfile/finder.go, internal/dockerfile/finder_test.go, tests/snapshots/nodejs-docusaurus.txt, tests/snapshots/nodejs-foal.txt, tests/snapshots/nodejs-medusa-zb.txt, tests/snapshots/nodejs-medusa.txt, tests/snapshots/nodejs-qwik-city.txt, tests/snapshots/nodejs-remix.txt, tests/snapshots/python-django-static-whitenoise.txt, tests/snapshots/python-django-static.txt, tests/snapshots/python-django.txt, tests/snapshots/python-fastapi.txt, tests/snapshots/python-flask-mysql.txt, tests/snapshots/python-flask-static.txt, tests/snapshots/python-flask.txt, tests/snapshots/python-streamlit.txt
We search for `Dockerfile.[name]` and `[name].Dockerfile` first, then `Dockerfile`.
- Closes ZEA-5985
=> ZEA-5985: zbpack uses general Dockerfile instead of explicit-specified Dockerfile (xxx.Dockerfile)
